-- Initial schema
CREATE TABLE IF NOT EXISTS users (id UUID PRIMARY KEY, email VARCHAR(255) UNIQUE NOT NULL, name VARCHAR(255), credits INTEGER DEFAULT 100, plan VARCHAR(50) DEFAULT 'free', created_at TIMESTAMP DEFAULT NOW());
